# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Pessoa - CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('contato', models.CharField(max_length=16, verbose_name='Contato')),
            ],
        ),
    ]
