# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mensalidade')),
                ('dia_mensalidade', models.IntegerField(verbose_name='Dia da Mensalidade')),
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academia.Pessoa', verbose_name='Cliente - CPF')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaSaidaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(default=datetime.date.today, verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', unique_for_date='data_entrada')),
            ],
        ),
        migrations.CreateModel(
            name='ReceberMensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('confirmacao', models.BooleanField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente', unique_for_month='data_recebimento', verbose_name='CPF')),
            ],
        ),
    ]
